### ISSUE TITLE
New category & 2 submissions.

### ISSUE THREAD

**Issue by medtinker** [sidmani/zencyclopedia#4]
Wanted to propose a new category - "**Medical Sciences**". You mentioned wanting to diversify the fields on the list. It'll definitely make a great addition. 

And to inaugurate the new category:

https://medtinker.net/how-learning-works/
A first-principle approach to neuroscience. The basics of neuronal structure, signaling and plasticity in a straightforward manner.

https://medtinker.net/mneumomedical-study-tips/
The follow up to the first guide, practical memorization techniques taking advantage of physiological neuroplasticity.

Thoughts?

Best regards,
Alan

**Comment by sidmani** [comment]
Those resources look great! What do you think about "Biology" as a category title though? I feel like it would act as a better catch-all for anything related to that field.

**Comment by medtinker** [comment]
"**Biology**" seems more appropriate, I agree.
The website is about first-principle approaches to medical sciences while framing them in practical situations. For example the first link above, is an introduction to neuroplasticity framed as an article on how learning works. The second link is closer to a more traditional guide on improving study habits.

We do take care to write them as in-depth and well referenced as possible while still keeping an introductory tone on the matter. Plus we make sure to keep them updated if we ever find the content lacking or out of date.

I admit the style might be a bit different but it does provide a nice middle ground between advanced concepts and more layman pieces.

**Comment by sidmani** [comment]
Thanks for the explanation! I think linking to the home page would be the most straightforward, instead of adding links to each article. Something like this:
## Biology
### General
**[Medtinker](https://medtinker.net)**  
\<description\>

Do you want to make the pull request?

**Comment by sidmani** [comment]
Your description is fine, but you have to actually edit the file and commit the changes. [Here's](https://yangsu.github.io/pull-request-tutorial/) a guide. Basically, fork the repository, make your changes, commit them, and then make a pull request between the edit branch on your fork and the edit branch on the main repo. (You've made a request between the edit and master branches on the main repo).  
Alternatively, if you're not comfortable with git, I can make the necessary changes 😁

**Comment by medtinker** [comment]
Yeah, if you could handle the changes I'd appreciate that a lot. Thought I could figure it out by myself.

I'll still read up the guide, thanks. :)

**Comment by sidmani** [comment]
Done. Would appreciate it if you spread the word about the Zencyclopedia too, especially if you know people working on similar projects 😁

**Comment by medtinker** [comment]
We added zencylopedia on our [list of projects](https://medtinker.net/indirect-support/) we urge people to visit. 😁 

Also we gave you out a shout-out on social media: [facebook](https://www.facebook.com/medtinker/posts/202903483841406), [twitter](https://twitter.com/medtinker/status/997128938861318150), [reddit](https://www.reddit.com/user/medtinker/comments/8k4wxt/weve_just_added_medtinker_to_zencyclopedia_a/?st=jhanz33l&sh=ba3f2b0c), [patreon](https://www.patreon.com/posts/18863356) and [linkedin](https://www.linkedin.com/feed/update/urn:li:activity:6402897320714866688).

Do keep in touch if you ever have any other idea that we might help you out with!

contact@medtinker.net
alin@medtinker.net
